FROM node:22-alpine

# Crear directorio de la app
WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el código
COPY . .

# Build del frontend (genera /dist)
RUN npm run build || cat /app/npm-debug.log

# Exponer puerto backend
EXPOSE 3000

# Comando de inicio
CMD ["node", "back/server.js"]
